submit: App
streamers:
  'output/Trump FUMBLES through 2nd speech at World Economic Forum #shorts/output_sub.mp4':
    copyright: 1
    source: null
    tid: 208
    cover: 'output/Trump FUMBLES through 2nd speech at World Economic Forum #shorts/Trump
      FUMBLES through 2nd speech at World Economic Forum #shorts_new.png'
    title: '[时事观察] 特朗普世经论坛演讲再“失言”？ | 双语精校'
    desc: 深度国际时事解读，中英双语精校。内容仅供学习交流，欢迎点赞关注支持！
    tag: 每日英语新闻, 英语新闻, 英语学习, 川普, 马斯克, 咨询直通车, 社会观察局, 热点深度观察
    dtime: 1769405073
    open-elec: 1
  'output/Hosts mock ''MISERABLE'' criticism of ''MAGA BABY BOOM'' #shorts/output_sub.mp4':
    copyright: 1
    source: null
    tid: 208
    cover: 'output/Hosts mock ''MISERABLE'' criticism of ''MAGA BABY BOOM'' #shorts/Hosts
      mock ''MISERABLE'' criticism of ''MAGA BABY BOOM'' #shorts_new.png'
    title: '[政经观察] 抨击“MAGA婴儿潮”？辛辣回击！ | 双语精校'
    desc: 深度国际时事解读，中英双语精校。内容仅供学习交流，欢迎点赞关注支持！
    tag: 每日英语新闻, 英语新闻, 英语学习, 川普, 马斯克, 咨询直通车, 社会观察局, 热点深度观察
    dtime: 1769408673
    open-elec: 1
  output/Bitter cold will slam Canada with some lows plunging to -50 C/output_sub.mp4:
    copyright: 1
    source: null
    tid: 208
    cover: output/Bitter cold will slam Canada with some lows plunging to -50 C/Bitter
      cold will slam Canada with some lows plunging to -50 C_new.png
    title: '[国际瞭望]极寒骤降！加拿大冰封零下50度警报 | 双语精校'
    desc: 深度国际时事解读，中英双语精校。内容仅供学习交流，欢迎点赞关注支持！
    tag: 每日英语新闻, 英语新闻, 英语学习, 川普, 马斯克, 咨询直通车, 社会观察局, 热点深度观察
    dtime: 1769412273
    open-elec: 1
  output/France intercepts oil tanker in the Mediterranean Sea sailing from Russia/output_sub.mp4:
    copyright: 1
    source: null
    tid: 208
    cover: output/France intercepts oil tanker in the Mediterranean Sea sailing from
      Russia/France intercepts oil tanker in the Mediterranean Sea sailing from Russia_new.png
    title: '[环球视野]法军截获俄油轮，地中海暗流涌动 | 双语精校'
    desc: 深度国际时事解读，中英双语精校。内容仅供学习交流，欢迎点赞关注支持！
    tag: 每日英语新闻, 英语新闻, 英语学习, 川普, 马斯克, 咨询直通车, 社会观察局, 热点深度观察
    dtime: 1769415873
    open-elec: 1
  output/The Temper Trap – Giving Up Air/output_sub.mp4:
    copyright: 1
    source: null
    tid: 208
    cover: output/The Temper Trap – Giving Up Air/The Temper Trap – Giving Up Air_new.png
    title: '[国际观察] 澳洲乐队献声：经典摇滚再现，老炮不服输 | 双语精校'
    desc: 深度国际时事解读，中英双语精校。内容仅供学习交流，欢迎点赞关注支持！
    tag: 每日英语新闻, 英语新闻, 英语学习, 川普, 马斯克, 咨询直通车, 社会观察局, 热点深度观察
    dtime: 1769419473
    open-elec: 1
  output/New Venezuelan leader spoke to Trump administration for months before US removed Maduro： reports/output_sub.mp4:
    copyright: 1
    source: null
    tid: 208
    cover: output/New Venezuelan leader spoke to Trump administration for months before
      US removed Maduro： reports/New Venezuelan leader spoke to Trump administration
      for months before US removed Maduro： reports_new.png
    title: '[深度观察] 秘闻：委新领袖早与美接触数月。 | 双语精校'
    desc: 深度国际时事解读，中英双语精校。内容仅供学习交流，欢迎点赞关注支持！
    tag: 每日英语新闻, 英语新闻, 英语学习, 川普, 马斯克, 咨询直通车, 社会观察局, 热点深度观察
    dtime: 1769423073
    open-elec: 1
