submit: App
limit: 3
streamers:
  output/You’re not dumb enough to fall for this, right？/output_sub.mp4:
    copyright: 1
    no_reprint: 1
    tid: 208
    cover: output/You’re not dumb enough to fall for this, right？/You’re not dumb
      enough to fall for this, right？_new.png
    title: 【双语】别天真了！这招骗不了人。 | 12-28
    desc: 本频道分享中英双语时事内容，为英语学习提供素材。内容仅供交流，不代表任何立场。感谢点赞关注充电支持！
    tag: 英语新闻, 英语学习, 川普, 马斯克, 咨询直通车, 社会观察局, 热点深度观察
    dtime: 1766966400
    open-elec: 1
